; Generated by AutoGUI 2.2.0a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Add, MonthCal, x228 y13 w225 h160
Gui Add, Picture, x29 y9 w135 h111, C:\Users\Rob Acer Aspire 3\Pictures\rob-windows-10-user.png
Gui Add, Button, x120 y210 w80 h23, &OK

Gui Show, w481 h381, Window
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line
