; Generated by AutoGUI 2.2.0a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui -MinimizeBox -MaximizeBox +AlwaysOnTop +ToolWindow
Gui Color, 0x808080
Gui Add, MonthCal, x228 y13 w225 h160
Gui Add, Picture, x29 y9 w135 h111, C:\Users\Rob Acer Aspire 3\Pictures\rob-windows-10-user.png
Gui Add, Button, x120 y210 w80 h23, &OK
Gui Add, ListBox, x302 y178 w152 h160, ListBox|one | |two | three
Gui Add, Text, x26 y164 w198 h2 0x10
Gui Add, Edit, x37 y252 w130 h93, this is some text
Gui Add, Link, x43 y178 w120 h23, <a href="https://autohotkey.com">autohotkey.com</a>
Gui Add, StatusBar,

Gui Show, w481 h381, Window
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line